name: NodeJs App Terraform Deploy

on:
  pull_request:
    types: [labeled]
  push:
    branches: [main]
  
env:
  DOCKER_IMAGE_NAME: nodeapp:latest
  IMAGE_REGISTRY_URL: ghcr.io
  # AZURE_WEBAPP_NAME: Zohair-Amravatiwala-ttt-app

jobs:
  Dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment: Dev
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}